basePath: /
definitions:
  http.BannerResponse:
    properties:
      bannerID:
        type: integer
    type: object
  http.BannerSlotRequest:
    properties:
      bannerID:
        type: integer
      slotID:
        type: integer
    type: object
  http.BaseAdminDescriptionRequest:
    properties:
      description:
        type: string
    type: object
  http.TrackRequest:
    properties:
      bannerID:
        type: integer
      sdgroupID:
        type: integer
      slotID:
        type: integer
    type: object
  http.TypicalResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a Banner Advertising Service
  title: Banner Advertising Service
  version: "1.0"
paths:
  /:
    get:
      description: Проверит доступность сервиса по показу баннерной рекламы
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Доступность сервиса
      tags:
      - Base
  /api/v1/banner:
    post:
      description: Добавляет новый баннер
      parameters:
      - description: Banner description
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/http.BaseAdminDescriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Добавить баннер
      tags:
      - Admin Banners
  /api/v1/banner-slot:
    delete:
      description: Удаляет баннер из ротации в данном слоте
      parameters:
      - description: SlotID and BannerID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/http.BannerSlotRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Удалить баннер из ротации
      tags:
      - Admin
    post:
      description: Добавляет новый баннер в ротацию в данном слоте
      parameters:
      - description: BannerID and SlotID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/http.BannerSlotRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Добавить баннер в ротацию
      tags:
      - Admin
  /api/v1/banner/{id}:
    delete:
      description: Удаляет баннер
      parameters:
      - description: Banner ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Удалить баннер
      tags:
      - Admin Banners
  /api/v1/group:
    post:
      description: Добавляет новую Социал-демографическую группу
      parameters:
      - description: SDGroupID description
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/http.BaseAdminDescriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Добавить группу
      tags:
      - Admin Groups
  /api/v1/group/{id}:
    delete:
      description: Удаляет Социал-демографическую группу
      parameters:
      - description: SDGroupID ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Удалить группу
      tags:
      - Admin Groups
  /api/v1/show-banner/{slot_id}/{sd_group_id}:
    get:
      description: Возвращает баннер, для показать в указанном слоте для указанной
        соц-дем. группы
      parameters:
      - description: Slot ID
        in: path
        name: slot_id
        required: true
        type: integer
      - description: Group ID
        in: path
        name: sd_group_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.BannerResponse'
        "400":
          description: Bad Request
      summary: Выбрать баннер для показа
      tags:
      - Base
  /api/v1/slot:
    post:
      description: Добавляет новый слот
      parameters:
      - description: Slot description
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/http.BaseAdminDescriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Добавить слот
      tags:
      - Admin Slots
  /api/v1/slot/{id}:
    delete:
      description: Удаляет слот
      parameters:
      - description: Slot ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Удалить слот
      tags:
      - Admin Slots
  /api/v1/track:
    post:
      description: Увеличивает счетчик переходов на 1 для указанного баннера в данном
        слоте в указанной группе.
      parameters:
      - description: SlotID, BannerID and SDGroupID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/http.TrackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.TypicalResponse'
        "400":
          description: Bad Request
      summary: Засчитать переход
      tags:
      - Tracker
swagger: "2.0"
